export default [
    {
        id: "001",
        x: 0,
        y: 0,
        w: 80,
        h: 80,
        text: "hello",
        shapeFamily: "polygon",
    },
    {
        id: "002",
        x: 0,
        y: 0,
        w: 80,
        h: 80,
        text: "world",
        shapeFamily: "polygon",
    },
    {
        id: "003",
        x: 0,
        y: 0,
        w: 80,
        h: 80,
        text: "hello",
        shapeFamily: "polygon",
    },
    {
        id: "004",
        x: 0,
        y: 0,
        w: 80,
        h: 80,
        text: "hello",
        shapeFamily: "polygon",
    },
    {
        id: "005",
        x: 0,
        y: 0,
        w: 80,
        h: 80,
        text: "hello",
        shapeFamily: "polygon",
    },
    {
        id: "006",
        x: 0,
        y: 0,
        w: 80,
        h: 80,
        text: "hello",
        shapeFamily: "polygon",
    },
    {
        id: "007",
        x: 0,
        y: 0,
        w: 80,
        h: 80,
        text: "hello",
        shapeFamily: "polygon",
    },
    {
        id: "008",
        x: 0,
        y: 0,
        w: 80,
        h: 80,
        text: "hello",
        shapeFamily: "polygon",
    },
    {
        id: "009",
        x: 0,
        y: 0,
        w: 80,
        h: 80,
        text: "hello",
        shapeFamily: "polygon",
    },
    {
        id: "010",
        x: 0,
        y: 0,
        w: 80,
        h: 80,
        text: "hello",
        shapeFamily: "polygon",
    },
]